# Generated by Django 2.1.4 on 2019-05-11 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(default='北京大学', max_length=50, verbose_name='所属学校')),
                ('work_position', models.CharField(max_length=50, verbose_name='职称')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('points', models.CharField(max_length=50, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(default='', upload_to='lecturer/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
        migrations.CreateModel(
            name='SchoolName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('desc', models.TextField(verbose_name='学校描述')),
                ('category', models.CharField(choices=[('one', '国内名校'), ('two', '普通本科院校'), ('three', '普通专科院校')], default='one', max_length=20, verbose_name='学校类别')),
                ('tag', models.CharField(default='国内名校', max_length=10, verbose_name='学校标签')),
                ('image', models.ImageField(upload_to='school/%Y/%m', verbose_name='Logo')),
                ('address', models.CharField(max_length=150, verbose_name='学校地址')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '学校名称',
                'verbose_name_plural': '学校名称',
            },
        ),
        migrations.AddField(
            model_name='lecturer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolName', verbose_name='所属学校'),
        ),
    ]
