# Generated by Django 2.1.4 on 2019-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='work_company',
            field=models.CharField(default='北京大学', max_length=50, verbose_name='所属学校'),
        ),
    ]
