# Generated by Django 2.1.4 on 2019-05-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prepare',
            field=models.CharField(default='什么都不需要准备，带着一颗好学的心，可以学会你想要的', max_length=300, verbose_name='课前准备'),
        ),
        migrations.AddField(
            model_name='course',
            name='reference',
            field=models.CharField(default='参考资料如下：', max_length=300, verbose_name='参考资料'),
        ),
        migrations.AddField(
            model_name='course',
            name='target',
            field=models.CharField(default='期望你什么都可以学会，未来可期，加油', max_length=300, verbose_name='授课目标'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolName', verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='从现在开始努力，未来可期', max_length=300, verbose_name='讲师有话说'),
        ),
    ]
