# Generated by Django 2.1.4 on 2019-05-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190511_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='http://jdvodrvfb210d.vod.126.net/mooc-video/nos/mp4/2016/07/15/1004675001_2fd2c2f7cd1f4ae5919593adee0db8b3_shd.mp4', max_length=200, verbose_name='访问地址'),
        ),
    ]
